### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by michael-trinity** [Cinchoo/ChoEazyCopy#21]
Trying to open the .exe results in the following error. I have the required .NET framework installed.
Previous versions result in the same issue.

`Unhandled Exception: Cinchoo.Core.ChoFatalApplicationException: Application failed to discover ApplicationHost object (Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.). ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Cinchoo.Core.ChoApplication.DiscoverAppHost()
   --- End of inner exception stack trace ---
   at Cinchoo.Core.ChoApplication.DiscoverAppHost()
   at Cinchoo.Core.ChoApplication.Run(String[] args, Nullable`1 applicationMode)
   at ChoEazyCopy.AppHost.Main(String[] args)`

Any idea what can cause this?

**Comment by Cinchoo** [comment]
Looks like something missing / some privilege issues. 
Pls turn on the log. Here is how you can do it

1. Open ChoEazyCopy.exe.Config file
2. Edit and the set the `ChoSwitch` value to 4

`<add name="ChoSwitch" value="4"/>`

This option enable the application to produce log files. run and capture the errors. Let me know.

**Comment by cryolithic** [comment]
Looks like it's trying to access event log?
`2021-08-13 03:39:14.9619079, System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  To create the source, you need permission to read all event logs to make sure that the new source name is unique.  Inaccessible logs: Security, State.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLogInternal.VerifyAndCreateSource(String sourceName, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message)
   at Cinchoo.Core.ChoApplication.WriteToEventLog(String message)
The Zone of the assembly that failed was:
MyComputer
2021-08-13 03:39:14.9739059, ChoEazyCopy.exe Information: 0 : 2021-08-13 03:39:14.9739059, Using AppConfigPath: E:\dev\portable apps\Config\ChoEazyCopy.exe.xml
2021-08-13 03:39:15.0329140, Error loading types from 'Dragablz, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' assembly.
2021-08-13 03:39:15.0339068, [Write]: 
`

**Comment by andychin7777** [comment]
[9560.zip](https://github.com/Cinchoo/ChoEazyCopy/files/12195557/9560.zip)
@Cinchoo I suddenly am running into this issue now as well, not sure what changed on my PC. 
Cheers,

**Comment by hdjdb** [comment]
I am also getting this issue, even on my backed up versions of the application. Probably an OS update.
